# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f46cc43bec0da4cad87ad36e009036c5"
name = "cart-transform-app"
handle = "cart-transform-app-45"
application_url = "https://example.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "ram-bundle.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
